name: Publish
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        working-directory: ./tests
        run: |
          docker build -f Dockerfile -t test-runner ..
          docker create --name extract test-runner
      - name: Run tests
        run: |
          docker run test-runner
      - name: Extract artifacts
        run: |
          docker cp extract:/src/runtime/deno-lambda-layer.zip deno-lambda-layer.zip
          docker cp extract:/src/runtime/deno-lambda-example.zip deno-lambda-example.zip
      - name: Verify Release Version Matches Deno Version
        run: |
          export DENO_LAMBDA_VERSION=1.10.3
          docker run -e DENO_LAMBDA_VERSION=$DENO_LAMBDA_VERSION test-runner _deno test --allow-env /src/tests/version_check.ts
      - name: Publish to SAR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DENO_LAMBDA_BUCKET: ${{ secrets.DENO_LAMBDA_BUCKET }}
        run: |
          export DENO_LAMBDA_VERSION=1.10.3
          echo tag: $DENO_LAMBDA_VERSION
          # FIXME: Installation of sam is fiddly.
          export DEBIAN_FRONTEND=noninteractive
          sudo apt -qq update
          sudo apt -qq install -y awscli python3-setuptools python3-testresources
          pip3 -q install -U --force pip
          export PATH=/home/runner/.local/bin:$PATH
          export SAM_CLI_TELEMETRY=1
          python3 -m pip -q install --user aws-sam-cli
          export AWS_EC2_METADATA_DISABLED=true
          aws s3 cp --quiet deno-lambda-layer.zip s3://$DENO_LAMBDA_BUCKET/deno-lambda-layer_$DENO_LAMBDA_VERSION.zip --acl public-read
          aws s3 cp --quiet deno-lambda-example.zip s3://$DENO_LAMBDA_BUCKET/deno-lambda-example_$DENO_LAMBDA_VERSION.zip --acl public-read
          echo ---
          cd SAR
          sed -i -e s/DENO_LAMBDA_BUCKET/$DENO_LAMBDA_BUCKET/g template.yml
          sed -i -e s/DENO_LAMBDA_VERSION/$DENO_LAMBDA_VERSION/g template.yml
          cat template.yml
          sam publish --region us-east-1
          echo ---
          cd blueprint
          sed -i -e s/DENO_LAMBDA_BUCKET/$DENO_LAMBDA_BUCKET/g template.yml
          sed -i -e s/DENO_LAMBDA_VERSION/$DENO_LAMBDA_VERSION/g template.yml
          cat template.yml
          sam publish --region us-east-1
          echo ---
